# Generated by Django 4.1.7 on 2023-03-29 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='')),
                ('Title', models.CharField(max_length=50)),
                ('Text', models.CharField(max_length=100)),
                ('Link', models.URLField(max_length=100)),
                ('Added_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Mixes',
        ),
    ]
