# Generated by Django 4.1.7 on 2023-03-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_mix_delete_mixes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='mix',
            name='Image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
