# Generated by Django 4.1.7 on 2023-03-29 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_subscribers_alter_mix_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribers',
            new_name='Subscriber',
        ),
    ]
