# Generated by Django 4.1.7 on 2023-03-31 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_rename_subscribers_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='images/')),
                ('Name', models.CharField(max_length=50)),
                ('Text', models.CharField(max_length=1000000)),
                ('Added_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
