# Generated by Django 4.1.7 on 2023-04-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='Full_Article',
            field=models.CharField(default='/', max_length=100),
        ),
    ]
