# Generated by Django 4.1.7 on 2023-04-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_remove_artist_full_article_artist_facebook_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='Youtube_Channel_Link',
            field=models.URLField(default='/', max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Facebook_Link',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Spotify_Link',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Twitter_Link',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Youtube_Video',
            field=models.URLField(max_length=100),
        ),
    ]
