# Generated by Django 4.1.7 on 2023-06-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0013_remove_article_text_article_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Text',
            field=models.CharField(default='/', max_length=100),
            preserve_default=False,
        ),
    ]
