# Generated by Django 4.1.7 on 2023-06-15 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0014_article_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mix',
        ),
    ]
