# Generated by Django 3.2.1 on 2024-01-10 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0015_delete_mix'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Track',
        ),
    ]
